version: "3.8"

services:
  exchange-app:
    # 這裡會讀取目錄下的 Dockerfile 進行打包
    build: .
    container_name: jpy-exchange-dashboard
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
